export const INITIALIZE_TABLE = "INITIALIZE_TABLE";
export const TABLE_LOAD_NEXT = "LOAD_NEXT";
export const TABLE_LOAD_PREVIOUS = "LOAD_PREVIOUS";
export const TABLE_SORT_ASC = "TABLE_SORT_ASC";
export const TABLE_SORT_DESC = "TABLE_SORT_DESC";
